import { RawTeam } from "./types";

export const sampleTeams: RawTeam[] = [
  { teamName: "TNFFM Titans", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=TNFFM-Titans", kills: 1280, booyahs: 34, championships: 6, runnerUp: 3, secondRunnerUp: 2, grandFinals: 9, winRate: 78, killRatio: 4.9, players: 5, description: "The flagship squad known for disciplined rotations, late-zone control, and explosive finals pressure.", bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1600&auto=format&fit=crop" },
  { teamName: "Shadow Reapers", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Shadow-Reapers", kills: 1215, booyahs: 29, championships: 5, runnerUp: 4, secondRunnerUp: 3, grandFinals: 10, winRate: 74, killRatio: 4.6, players: 5, description: "A high-tempo roster that wins fights early and converts momentum into consistent podium finishes." },
  { teamName: "Phoenix Vortex", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Phoenix-Vortex", kills: 1188, booyahs: 27, championships: 4, runnerUp: 5, secondRunnerUp: 4, grandFinals: 11, winRate: 72, killRatio: 4.4, players: 6, description: "Known for resilient comeback runs and excellent clutch decision making in grand finals." },
  { teamName: "Apex Raiders", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Apex-Raiders", kills: 1132, booyahs: 26, championships: 3, runnerUp: 4, secondRunnerUp: 5, grandFinals: 8, winRate: 69, killRatio: 4.1, players: 5 },
  { teamName: "Royal Blitz", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Royal-Blitz", kills: 1097, booyahs: 24, championships: 3, runnerUp: 3, secondRunnerUp: 4, grandFinals: 8, winRate: 67, killRatio: 4.0, players: 5 },
  { teamName: "Inferno Kings", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Inferno-Kings", kills: 1055, booyahs: 21, championships: 3, runnerUp: 2, secondRunnerUp: 5, grandFinals: 7, winRate: 64, killRatio: 3.9, players: 6 },
  { teamName: "Nova Syndicate", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Nova-Syndicate", kills: 1014, booyahs: 20, championships: 2, runnerUp: 5, secondRunnerUp: 3, grandFinals: 9, winRate: 66, killRatio: 3.7, players: 5 },
  { teamName: "Velocity X", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Velocity-X", kills: 994, booyahs: 19, championships: 2, runnerUp: 4, secondRunnerUp: 3, grandFinals: 8, winRate: 63, killRatio: 3.6, players: 5 },
  { teamName: "Crimson Orbit", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Crimson-Orbit", kills: 962, booyahs: 18, championships: 2, runnerUp: 3, secondRunnerUp: 4, grandFinals: 7, winRate: 61, killRatio: 3.5, players: 6 },
  { teamName: "Mystic Havoc", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Mystic-Havoc", kills: 930, booyahs: 17, championships: 1, runnerUp: 5, secondRunnerUp: 4, grandFinals: 7, winRate: 60, killRatio: 3.4, players: 5 },
  { teamName: "Thunder Core", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Thunder-Core", kills: 902, booyahs: 16, championships: 1, runnerUp: 4, secondRunnerUp: 4, grandFinals: 7, winRate: 58, killRatio: 3.3, players: 5 },
  { teamName: "Omega Fang", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Omega-Fang", kills: 878, booyahs: 15, championships: 1, runnerUp: 3, secondRunnerUp: 5, grandFinals: 6, winRate: 57, killRatio: 3.2, players: 5 },
  { teamName: "Solar Venom", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Solar-Venom", kills: 850, booyahs: 14, championships: 1, runnerUp: 3, secondRunnerUp: 3, grandFinals: 6, winRate: 55, killRatio: 3.1, players: 4 },
  { teamName: "Rogue Celestials", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Rogue-Celestials", kills: 822, booyahs: 13, championships: 1, runnerUp: 2, secondRunnerUp: 4, grandFinals: 5, winRate: 54, killRatio: 3.0, players: 5 },
  { teamName: "Frost Legion", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Frost-Legion", kills: 790, booyahs: 12, championships: 0, runnerUp: 4, secondRunnerUp: 4, grandFinals: 5, winRate: 52, killRatio: 2.9, players: 5 },
  { teamName: "Nightfall Crew", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Nightfall-Crew", kills: 764, booyahs: 11, championships: 0, runnerUp: 3, secondRunnerUp: 4, grandFinals: 5, winRate: 51, killRatio: 2.8, players: 6 },
  { teamName: "Eclipse Nine", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Eclipse-Nine", kills: 738, booyahs: 10, championships: 0, runnerUp: 3, secondRunnerUp: 3, grandFinals: 4, winRate: 49, killRatio: 2.7, players: 5 },
  { teamName: "Rapid Zenith", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Rapid-Zenith", kills: 702, booyahs: 9, championships: 0, runnerUp: 2, secondRunnerUp: 3, grandFinals: 4, winRate: 48, killRatio: 2.6, players: 4 },
  { teamName: "Chaos Unit", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Chaos-Unit", kills: 675, booyahs: 8, championships: 0, runnerUp: 2, secondRunnerUp: 2, grandFinals: 3, winRate: 46, killRatio: 2.5, players: 5 },
  { teamName: "Viper Nexus", logoUrl: "https://api.dicebear.com/8.x/shapes/svg?seed=Viper-Nexus", kills: 642, booyahs: 7, championships: 0, runnerUp: 1, secondRunnerUp: 3, grandFinals: 3, winRate: 45, killRatio: 2.4, players: 5 }
];
