/* TNFFM COMMUNITY RANKING - CANONICAL GOOGLE APPS SCRIPT API */
const VERSION='TNFFM-2026.08.25-RESULTS-FIX';
const DEFAULT_LOGO_URL='/tnffm-default-logo.svg';
const DEFAULT_PLAYER_LOGO_URL='/tnffm-default-player.svg';
const TABS={TEAMS:'Teams',ROSTERS:'Team Rosters',RANKINGS:'Community Rankings',EVENTS:'Events',RESULTS:'Event Results',NEWS:'TournamentNews',COLLAB:'Collaborators',ACCOUNTS:'TeamAccounts',SUBMISSIONS:'Submissions',FEEDBACK:'Feedback'};
const HEADERS={};
HEADERS[TABS.TEAMS]=['Team ID','Team Name','Slug','Logo URL','Banner URL','Description','Mobile Number','Status','Registration Status','Created At','Updated At'];
HEADERS[TABS.ROSTERS]=['Player ID','Team ID','Team Name','Player Name','UID','Role','Player Logo URL','Status','Created At','Updated At'];
HEADERS[TABS.RANKINGS]=['Rank','Team ID','Team Name','Slug','Events Played','Championships','Runner-Up','2nd Runner-Up','Top 5 Finishes','Community Score','Kills','Booyahs','Kill Ratio','Booyah Ratio','Position Points','Total Points','Matches Played','Grand Finals','Win Rate','Eligible','Status','Updated At'];
HEADERS[TABS.EVENTS]=['Event ID','Name','Organizer','Teams','Prize','Status','Counted','Date','Notes','Matches Played','Published','Results','Created At','Updated At'];
HEADERS[TABS.RESULTS]=['Result ID','Event ID','Event Name','Team ID','Team Name','Position','Kills','Booyahs','Position Points','Kill Points','Total Points','Proof URL','Verified','Updated At'];
HEADERS[TABS.NEWS]=['ID','Title','Description','Date','Type','Status','ImageURL','Link','UpdatedAt'];
HEADERS[TABS.COLLAB]=['Collaborator ID','Name','Role','Status','Contact','LogoURL','Website','Instagram','UpdatedAt'];
HEADERS[TABS.ACCOUNTS]=['Username','PasswordHash','TeamSlug','Email','Status','CreatedAt','UpdatedAt'];
HEADERS[TABS.SUBMISSIONS]=['SubmissionID','Username','TeamSlug','Team','TournamentName','TournamentDate','OrganizerName','PrizePool','FinalPosition','FinalLeaderboard','ProofURL','Status','ReviewNotes','ReviewedBy','ReviewedAt','CreatedAt'];
HEADERS[TABS.FEEDBACK]=['FeedbackID','Username','TeamSlug','Team','Message','Status','AdminReply','CreatedAt','UpdatedAt'];
function getSpreadsheet_(){const id=String(PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID')||'').trim();if(id)return SpreadsheetApp.openById(id);const active=SpreadsheetApp.getActiveSpreadsheet();if(active)return active;throw new Error('Google Sheet is not configured. Set Script Property SPREADSHEET_ID.');}
function json_(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON);}
function clean_(v){return v==null?'':String(v).trim();}
function num_(v,d){const n=Number(v);return Number.isFinite(n)?n:(d==null?0:d);}
function int_(v){return Math.max(0,Math.floor(num_(v,0)));}
function now_(){return new Date().toISOString();}
function error_(e){return String(e&&e.message?e.message:e);}
function sheet_(ss,name){return ss.getSheetByName(name)||ss.insertSheet(name);}
function ensure_(s,headers){if(s.getMaxColumns()<headers.length)s.insertColumnsAfter(s.getMaxColumns(),headers.length-s.getMaxColumns());s.getRange(1,1,1,headers.length).setValues([headers]);s.setFrozenRows(1);}
function rows_(s){if(!s||s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).getValues();}
function safeJson_(v,fallback){if(Array.isArray(v))return v;if(!v)return fallback;try{return JSON.parse(String(v));}catch(_){return fallback;}}
function slugify_(name){const s=clean_(name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,45);return s||'team';}
function storedLogo_(url){const v=clean_(url);return !v||v===DEFAULT_LOGO_URL?'':v;}
function displayLogo_(url){return clean_(url)||DEFAULT_LOGO_URL;}
function storedPlayerLogo_(url){const v=clean_(url);return !v||v===DEFAULT_PLAYER_LOGO_URL||v===DEFAULT_LOGO_URL?'':v;}
function displayPlayerLogo_(url){return clean_(url)||DEFAULT_PLAYER_LOGO_URL;}
function setupTNFFM(){const ss=getSpreadsheet_();Object.keys(HEADERS).forEach(n=>ensure_(sheet_(ss,n),HEADERS[n]));SpreadsheetApp.flush();return json_({ok:true,version:VERSION,message:'TNFFM Google Sheet structure is ready.'});}
function setupSheets(){return setupTNFFM();}
function readTeams_(ss){const s=sheet_(ss,TABS.TEAMS);ensure_(s,HEADERS[TABS.TEAMS]);const rs=readRosters_(ss),out=[];rows_(s).forEach(r=>{if(!clean_(r[1]))return;const id=clean_(r[0]);out.push({teamId:id,teamName:clean_(r[1]),slug:clean_(r[2])||slugify_(r[1]),logoUrl:storedLogo_(r[3]),bannerUrl:clean_(r[4]),description:clean_(r[5]),mobileNumber:clean_(r[6]),status:clean_(r[7])||'Active',registrationStatus:clean_(r[8])||'Registered',createdAt:clean_(r[9]),updatedAt:clean_(r[10]),roster:rs[id]||[]});});return out;}
function readRosters_(ss){const s=sheet_(ss,TABS.ROSTERS);ensure_(s,HEADERS[TABS.ROSTERS]);const out={};rows_(s).forEach(r=>{const id=clean_(r[1]);if(!id)return;(out[id]||(out[id]=[])).push({playerId:clean_(r[0]),name:clean_(r[3]),uid:clean_(r[4]),role:clean_(r[5]),playerLogoUrl:storedPlayerLogo_(r[6]),status:clean_(r[7])||'Active',createdAt:clean_(r[8]),updatedAt:clean_(r[9])});});return out;}
function writeRosters_(ss,teams){const s=sheet_(ss,TABS.ROSTERS);ensure_(s,HEADERS[TABS.ROSTERS]);if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,HEADERS[TABS.ROSTERS].length).clearContent();const out=[];(teams||[]).forEach(t=>{const id=clean_(t.teamId||t.id);const roster=Array.isArray(t.roster)?t.roster:safeJson_(t.roster,[]);roster.forEach((p,j)=>{if(!p)return;const name=clean_(p.name||p.playerName),uid=clean_(p.uid||p.UID),logo=storedPlayerLogo_(p.playerLogoUrl||p.PlayerLogoURL||p.playerLogo||p.logoUrl);if(!name&&!uid&&!logo)return;out.push([clean_(p.playerId||p.id)||id+'-P-'+String(j+1).padStart(2,'0'),id,clean_(t.teamName||t.Team),name,uid,clean_(p.role),logo,clean_(p.status)||'Active',clean_(p.createdAt)||now_(),now_()]);});});if(out.length)s.getRange(2,1,out.length,HEADERS[TABS.ROSTERS].length).setValues(out);}
function writeTeams_(ss,teams){const s=sheet_(ss,TABS.TEAMS);ensure_(s,HEADERS[TABS.TEAMS]);const old=readTeams_(ss),bySlug={};old.forEach(t=>bySlug[t.slug]=t);const out=(teams||[]).map((t,i)=>{const slug=clean_(t.slug||t.Slug)||slugify_(t.teamName||t.Team),prior=bySlug[slug]||{};return[clean_(t.teamId||t.id)||prior.teamId||'TN-'+String(i+1).padStart(5,'0'),clean_(t.teamName||t.Team),slug,storedLogo_(t.logoUrl!==undefined?t.logoUrl:t['Logo URL']),clean_(t.bannerUrl!==undefined?t.bannerUrl:t['Banner URL']),clean_(t.description!==undefined?t.description:t.Description),clean_(t.mobileNumber!==undefined?t.mobileNumber:t['Mobile Number']),clean_(t.status||t.Status)||'Active',clean_(t.registrationStatus)||'Registered',prior.createdAt||now_(),now_()];});if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,HEADERS[TABS.TEAMS].length).clearContent();if(out.length)s.getRange(2,1,out.length,HEADERS[TABS.TEAMS].length).setValues(out);writeRosters_(ss,teams||[]);}
function readRankings_(ss){const s=sheet_(ss,TABS.RANKINGS);ensure_(s,HEADERS[TABS.RANKINGS]);return rows_(s).filter(r=>clean_(r[2])).map(r=>({rank:int_(r[0]),teamId:clean_(r[1]),teamName:clean_(r[2]),slug:clean_(r[3]),eventsPlayed:int_(r[4]),championships:int_(r[5]),runnerUp:int_(r[6]),secondRunnerUp:int_(r[7]),top5Finishes:int_(r[8]),communityScore:num_(r[9]),kills:int_(r[10]),booyahs:int_(r[11]),killRatio:num_(r[12]),booyahRatio:num_(r[13]),positionPoints:num_(r[14]),totalPoints:num_(r[15]),matchesPlayed:int_(r[16]),grandFinals:int_(r[17]),winRate:num_(r[18]),eligible:clean_(r[19])||'Yes',status:clean_(r[20])||'Active',updatedAt:clean_(r[21])}));}
function writeRankings_(ss,rankings){const s=sheet_(ss,TABS.RANKINGS);ensure_(s,HEADERS[TABS.RANKINGS]);if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,HEADERS[TABS.RANKINGS].length).clearContent();const teams=readTeams_(ss),out=(rankings||[]).map((r,i)=>{const team=teams.find(t=>(clean_(r.slug)&&t.slug===clean_(r.slug))||t.teamName.toLowerCase()===clean_(r.teamName).toLowerCase())||{};return[int_(r.rank||i+1),clean_(r.teamId)||team.teamId,clean_(r.teamName)||team.teamName,clean_(r.slug)||team.slug,int_(r.eventsPlayed),int_(r.championships),int_(r.runnerUp),int_(r.secondRunnerUp||r['2nd Runner-Up']),int_(r.top5Finishes),num_(r.communityScore??r.communityPoints),int_(r.kills),int_(r.booyahs),num_(r.killRatio),num_(r.booyahRatio),num_(r.positionPoints),num_(r.totalPoints),int_(r.matchesPlayed),int_(r.grandFinals),num_(r.winRate),clean_(r.eligible)||'Yes',clean_(r.status)||'Active',now_()];});if(out.length)s.getRange(2,1,out.length,HEADERS[TABS.RANKINGS].length).setValues(out);}
function readEvents_(ss){const s=sheet_(ss,TABS.EVENTS);ensure_(s,HEADERS[TABS.EVENTS]);return rows_(s).filter(r=>clean_(r[1])).map(r=>({eventId:clean_(r[0]),name:clean_(r[1]),organizer:clean_(r[2]),teams:int_(r[3]),prize:clean_(r[4]),status:clean_(r[5]),counted:clean_(r[6]),date:clean_(r[7]),notes:clean_(r[8]),matchesPlayed:int_(r[9]),published:clean_(r[10]),results:safeJson_(r[11],[]),createdAt:clean_(r[12]),updatedAt:clean_(r[13])}));}
function writeEvents_(ss,events){const s=sheet_(ss,TABS.EVENTS);ensure_(s,HEADERS[TABS.EVENTS]);if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,HEADERS[TABS.EVENTS].length).clearContent();const out=(events||[]).map((e,i)=>[clean_(e.eventId||e.id)||'EV-'+String(i+1).padStart(5,'0'),clean_(e.name||e.eventName),clean_(e.organizer),int_(e.teams||e.teamCount),clean_(e.prize||e.prizePool),clean_(e.status)||'Confirmed',clean_(e.counted),clean_(e.date||e.eventDate),clean_(e.notes),int_(e.matchesPlayed),clean_(e.published),JSON.stringify(Array.isArray(e.results)?e.results:[]),clean_(e.createdAt)||now_(),now_()]);if(out.length)s.getRange(2,1,out.length,HEADERS[TABS.EVENTS].length).setValues(out);}
function normalizeResult_(r,i){const team=clean_(r&& (r.teamName||r.team));if(!team)return null;const rank=Math.max(1,int_(r.rank||r.position)||1),kills=int_(r.kills),booyahs=int_(r.booyahs),pp=num_(r.positionPoints),kp=num_(r.killPoints??kills),total=num_(r.totalPoints??r.total??pp+kp);return{resultId:clean_(r.resultId||r.id)||'RES-'+String(i+1).padStart(6,'0'),eventId:clean_(r.eventId),eventName:clean_(r.eventName),teamId:clean_(r.teamId),teamName:team,position:rank,kills,booyahs,positionPoints:pp,killPoints:kp,totalPoints:total,proofUrl:clean_(r.proofUrl||r.proofURL),verified:clean_(r.verified),updatedAt:now_()};}
function readResults_(ss){const s=sheet_(ss,TABS.RESULTS);ensure_(s,HEADERS[TABS.RESULTS]);return rows_(s).filter(r=>clean_(r[0])).map(r=>({resultId:clean_(r[0]),eventId:clean_(r[1]),eventName:clean_(r[2]),teamId:clean_(r[3]),teamName:clean_(r[4]),position:int_(r[5]),rank:int_(r[5]),kills:int_(r[6]),booyahs:int_(r[7]),positionPoints:num_(r[8]),killPoints:num_(r[9]),totalPoints:num_(r[10]),total:num_(r[10]),proofUrl:clean_(r[11]),verified:clean_(r[12]),updatedAt:clean_(r[13])}));}
function writeResults_(ss,results){const s=sheet_(ss,TABS.RESULTS);ensure_(s,HEADERS[TABS.RESULTS]);const normalized=(results||[]).map(normalizeResult_).filter(Boolean);if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,HEADERS[TABS.RESULTS].length).clearContent();const out=normalized.map(r=>[r.resultId,r.eventId,r.eventName,r.teamId,r.teamName,r.position,r.kills,r.booyahs,r.positionPoints,r.killPoints,r.totalPoints,r.proofUrl,r.verified,r.updatedAt]);if(out.length)s.getRange(2,1,out.length,HEADERS[TABS.RESULTS].length).setValues(out);return normalized;}
function resultsFromEvents_(events){const out=[];(events||[]).forEach((e,ei)=>{const evId=clean_(e.eventId||e.id)||'EV-'+String(ei+1).padStart(5,'0');const evName=clean_(e.name||e.eventName);(Array.isArray(e.results)?e.results:[]).forEach((r,ri)=>out.push(normalizeResult_(Object.assign({},r,{eventId:r&&r.eventId||evId,eventName:r&&r.eventName||evName}),ri+1)));});return out.filter(Boolean);}
function readObjects_(ss,name){const s=sheet_(ss,name);ensure_(s,HEADERS[name]);return rows_(s).map(r=>{const o={};HEADERS[name].forEach((h,i)=>o[h]=r[i]);return o;});}
function writeObjects_(ss,name,items){const s=sheet_(ss,name);ensure_(s,HEADERS[name]);if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,HEADERS[name].length).clearContent();const out=(items||[]).map(x=>HEADERS[name].map(h=>x[h]!=null?x[h]:''));if(out.length)s.getRange(2,1,out.length,HEADERS[name].length).setValues(out);}
function readNews_(ss){const s=sheet_(ss,TABS.NEWS);ensure_(s,HEADERS[TABS.NEWS]);return rows_(s).filter(r=>clean_(r[1])).map(r=>({id:clean_(r[0]),title:clean_(r[1]),description:clean_(r[2]),date:clean_(r[3]),type:clean_(r[4]),status:clean_(r[5]),imageUrl:clean_(r[6]),link:clean_(r[7]),updatedAt:clean_(r[8])}));}
function writeNews_(ss,items){const s=sheet_(ss,TABS.NEWS);ensure_(s,HEADERS[TABS.NEWS]);if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,HEADERS[TABS.NEWS].length).clearContent();const out=(items||[]).map((n,i)=>[clean_(n.id||n.ID)||'NEWS-'+String(i+1).padStart(5,'0'),clean_(n.title||n.Title),clean_(n.description||n.Description),clean_(n.date||n.Date),clean_(n.type||n.Type),clean_(n.status||n.Status)||'Published',clean_(n.imageUrl||n.ImageURL),clean_(n.link||n.Link),now_()]);if(out.length)s.getRange(2,1,out.length,HEADERS[TABS.NEWS].length).setValues(out);}
function saveAll_(ss,b){const lock=LockService.getScriptLock();lock.waitLock(20000);try{if(Array.isArray(b.teams))writeTeams_(ss,b.teams);if(Array.isArray(b.rankings))writeRankings_(ss,b.rankings);if(Array.isArray(b.events))writeEvents_(ss,b.events);let incomingResults=Array.isArray(b.results)?b.results:(Array.isArray(b.rankingResults)?b.rankingResults:[]);if(!incomingResults.length&&Array.isArray(b.events))incomingResults=resultsFromEvents_(b.events);const wroteResults=writeResults_(ss,incomingResults);if(Array.isArray(b.collaborators))writeObjects_(ss,TABS.COLLAB,b.collaborators);if(Array.isArray(b.news))writeNews_(ss,b.news);SpreadsheetApp.flush();const readBack={teams:readTeams_(ss),events:readEvents_(ss),results:readResults_(ss),rankings:readRankings_(ss),collaborators:readObjects_(ss,TABS.COLLAB),news:readNews_(ss)};const resultMismatch=Array.isArray(b.events)||Array.isArray(b.results)||Array.isArray(b.rankingResults);if(resultMismatch&&wroteResults.length!==readBack.results.length)throw new Error('Event Results was written, but the Event Results sheet read back '+readBack.results.length+' rows instead of '+wroteResults.length+'.');return json_({ok:true,verified:true,googleSheets:true,counts:{teams:readBack.teams.length,events:readBack.events.length,eventResults:readBack.results.length,rankings:readBack.rankings.length},readBack:readBack,message:'Saved to Google Sheets and verified successfully.'});}finally{lock.releaseLock();}}
function doGet(){try{const ss=getSpreadsheet_();setupTNFFM();return json_({ok:true,version:VERSION,teams:readTeams_(ss),events:readEvents_(ss),results:readResults_(ss),rankings:readRankings_(ss),collaborators:readObjects_(ss,TABS.COLLAB),news:readNews_(ss),defaultLogoUrl:DEFAULT_LOGO_URL,defaultPlayerLogoUrl:DEFAULT_PLAYER_LOGO_URL,serverTime:now_()});}catch(e){return json_({ok:false,version:VERSION,message:error_(e)});}}
function doPost(e){try{if(!e||!e.postData||!e.postData.contents)return json_({ok:false,message:'Request body is missing.'});const b=JSON.parse(e.postData.contents||'{}'),action=clean_(b.action).toLowerCase(),ss=getSpreadsheet_();switch(action){case'setup':return setupTNFFM();case'ping':return json_({ok:true,version:VERSION,time:now_()});case'getdata':return doGet();case'saveranking':return saveRanking_(ss,b);case'save':case'sync':case'saveall:return saveAll_(ss,b);default:if(Array.isArray(b.teams)||Array.isArray(b.events)||Array.isArray(b.results)||Array.isArray(b.rankingResults)||Array.isArray(b.rankings)||Array.isArray(b.collaborators)||Array.isArray(b.news))return saveAll_(ss,b);return json_({ok:false,version:VERSION,message:'Unknown action: '+action});}}catch(e){return json_({ok:false,version:VERSION,message:error_(e)});}}
function saveRanking_(ss,b){if(Array.isArray(b.results)||Array.isArray(b.rankingResults))writeResults_(ss,Array.isArray(b.results)?b.results:b.rankingResults);if(Array.isArray(b.rankings))writeRankings_(ss,b.rankings);SpreadsheetApp.flush();return json_({ok:true,verified:true,results:readResults_(ss),rankings:readRankings_(ss),message:'Ranking and Event Results saved and verified successfully.'});}
