/* TNFFM PERFORMANCE + TEAM ACTION PATCH
 * IMPORTANT: This patch is intended to be merged into the deployed Code.gs.
 * It optimizes the read path and adds the Team Dashboard actions required by
 * the current Next.js application. Do not deploy this file alone.
 */
var TNFFM_SS_CACHE_ = null;
function tnffmSpreadsheet_(){
  if(TNFFM_SS_CACHE_) return TNFFM_SS_CACHE_;
  var id=String(PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID')||'').trim();
  TNFFM_SS_CACHE_=id?SpreadsheetApp.openById(id):SpreadsheetApp.getActiveSpreadsheet();
  if(!TNFFM_SS_CACHE_) throw new Error('Google Sheet is not configured. Set SPREADSHEET_ID.');
  return TNFFM_SS_CACHE_;
}
function tnffmSheet_(name){var s=tnffmSpreadsheet_().getSheetByName(name);if(!s)throw new Error('Missing required sheet: '+name+'. Run setupTNFFM once.');return s;}
function tnffmTable_(name){var s=tnffmSheet_(name),data=s.getDataRange().getDisplayValues();if(!data.length)return[];var h=data[0].map(function(v){return String(v||'').trim();}),out=[];for(var r=1;r<data.length&&out.length<4999;r++){var row=data[r],used=false;for(var c=0;c<row.length;c++){if(String(row[c]||'').trim()!==''){used=true;break;}}if(!used)continue;var raw={};for(var i=0;i<h.length;i++)if(h[i])raw[h[i]]=row[i];out.push(raw);}return out;}
function tnffmCanon_(raw){var map={'Team ID':'teamId','Team Name':'teamName','Slug':'slug','Logo URL':'logoUrl','Banner URL':'bannerUrl','Description':'description','Mobile Number':'mobileNumber','Status':'status','Registration Status':'registrationStatus','Created At':'createdAt','Updated At':'updatedAt','Player ID':'playerId','Player Name':'playerName','UID':'uid','Role':'role','Player Logo URL':'playerLogoUrl','Rank':'rank','Events Played':'eventsPlayed','Championships':'championships','Runner-Up':'runnerUp','2nd Runner-Up':'secondRunnerUp','Top 5 Finishes':'top5Finishes','Community Score':'communityScore','Kills':'kills','Booyahs':'booyahs','Kill Ratio':'killRatio','Booyah Ratio':'booyahRatio','Position Points':'positionPoints','Total Points':'totalPoints','Matches Played':'matchesPlayed','Grand Finals':'grandFinals','Win Rate':'winRate','Eligible':'eligible','Event ID':'eventId','Name':'name','Organizer':'organizer','Teams':'teams','Prize':'prize','Counted':'counted','Date':'date','Notes':'notes','Published':'published','Results':'results','ID':'id','Title':'title','Type':'type','ImageURL':'imageUrl','Link':'link','Result ID':'resultId','Event Name':'eventName','Position':'position','Kill Points':'killPoints','Proof URL':'proofUrl','Verified':'verified','Username':'username','PasswordHash':'passwordHash','Email':'email','SubmissionID':'submissionId','TournamentName':'tournamentName','TournamentDate':'tournamentDate','OrganizerName':'organizerName','PrizePool':'prizePool','FinalPosition':'finalPosition','FinalLeaderboard':'finalLeaderboard','ProofURL':'proofUrl','ReviewNotes':'reviewNotes','ReviewedBy':'reviewedBy','ReviewedAt':'reviewedAt','FeedbackID':'feedbackId','Timestamp':'timestamp','Team':'team','Message':'message','AdminReply':'adminReply','Contact':'contact','Website':'website','Instagram':'instagram','Collaborator ID':'collaboratorId'};var o={};Object.keys(raw).forEach(function(k){var v=raw[k],x=String(v==null?'':v).trim(),c=map[k]||k;if(/^(true|false)$/i.test(x))v=x.toLowerCase()==='true';else if((x[0]==='['&&x[x.length-1]===']')||(x[0]==='{'&&x[x.length-1]==='}')){try{v=JSON.parse(x);}catch(e){}}o[c]=v;});return o;}
function tnffmSection_(name){return tnffmTable_(name).map(tnffmCanon_);}
function tnffmReadRosters_(){var out={};tnffmSection_(TABS.ROSTERS).forEach(function(p){var id=String(p.teamId||'').trim();if(!id)return;(out[id]||(out[id]=[])).push({playerId:String(p.playerId||''),name:String(p.playerName||p.name||''),uid:String(p.uid||''),role:String(p.role||''),playerLogoUrl:String(p.playerLogoUrl||''),status:String(p.status||'Active'),createdAt:String(p.createdAt||''),updatedAt:String(p.updatedAt||'')});});return out;}
function tnffmReadTeams_(){var roster=tnffmReadRosters_();return tnffmSection_(TABS.TEAMS).map(function(t){var id=String(t.teamId||''),name=String(t.teamName||'').trim();return{teamId:id,teamName:name,slug:String(t.slug||'').trim()||slugify_(name),logoUrl:String(t.logoUrl||''),bannerUrl:String(t.bannerUrl||''),description:String(t.description||''),mobileNumber:String(t.mobileNumber||''),status:String(t.status||'Active'),registrationStatus:String(t.registrationStatus||'Registered'),players:(roster[id]||[]).length,roster:roster[id]||[],createdAt:String(t.createdAt||''),lastUpdated:String(t.updatedAt||'')};}).filter(function(t){return t.teamName;});}
function tnffmReadAll_(){var rr=tnffmSection_(TABS.RESULTS);return{teams:tnffmReadTeams_(),rankings:tnffmSection_(TABS.RANKINGS),events:tnffmSection_(TABS.EVENTS),rankingResults:rr,results:rr,news:tnffmSection_(TABS.NEWS),collaborators:tnffmSection_(TABS.COLLAB),accounts:tnffmSection_(TABS.ACCOUNTS),submissions:tnffmSection_(TABS.SUBMISSIONS),feedback:tnffmSection_(TABS.FEEDBACK),serverTime:new Date().toISOString(),version:VERSION};}
function tnffmCachedGet_(){var cache=CacheService.getScriptCache(),key='tnffm_public_v3',hit=cache.get(key);if(hit){try{return JSON.parse(hit);}catch(e){}}var data=tnffmReadAll_(),encoded=JSON.stringify(data);if(encoded.length<95000)cache.put(key,encoded,15);return data;}
function tnffmInvalidate_(){try{CacheService.getScriptCache().remove('tnffm_public_v3');}catch(e){}}
function tnffmAccountRows_(){return tnffmSection_(TABS.ACCOUNTS);}
function tnffmRegisterTeam_(p){var username=String(p.username||'').trim().toLowerCase(),hash=String(p.passwordHash||''),name=String(p.teamName||'').trim(),email=String(p.email||'').trim().toLowerCase();if(!username||!hash||!name)throw new Error('Username, password and team name are required.');var a=tnffmAccountRows_();if(a.some(function(x){return String(x.username||'').toLowerCase()===username;}))throw new Error('Username is already registered.');var teams=tnffmReadTeams_(),slug=slugify_(name),base=slug,n=2;while(teams.some(function(t){return t.slug===slug;}))slug=base+'-'+n++;var id='TN-'+String(teams.length+1).padStart(5,'0');teams.push({teamId:id,teamName:name,slug:slug,logoUrl:'',bannerUrl:'',description:'',mobileNumber:'',status:'Active',registrationStatus:'Registered',roster:[],createdAt:new Date().toISOString()});writeTeams_(teams);a.push({username:username,passwordHash:hash,teamSlug:slug,email:email,status:'Active',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});writeGeneric_(TABS.ACCOUNTS,a);tnffmInvalidate_();return ok_({username:username,teamSlug:slug,teamName:name,message:'Team account created successfully.'});}
function tnffmLogin_(p){var username=String(p.username||'').trim().toLowerCase(),hash=String(p.passwordHash||''),a=tnffmAccountRows_().find(function(x){return String(x.username||'').toLowerCase()===username;});if(!a||String(a.status||'Active').toLowerCase()==='disabled'||String(a.passwordHash||'')!==hash)throw new Error('Invalid username or password.');return ok_({username:username,teamSlug:String(a.teamSlug||''),message:'Login successful.'});}
function tnffmChangePassword_(p){var u=String(p.username||'').trim().toLowerCase(),a=tnffmAccountRows_(),x=a.find(function(v){return String(v.username||'').toLowerCase()===u;});if(!x)throw new Error('Team account not found.');if(String(x.passwordHash||'')!==String(p.currentPasswordHash||''))throw new Error('Current password is incorrect.');x.passwordHash=String(p.newPasswordHash||'');x.updatedAt=new Date().toISOString();writeGeneric_(TABS.ACCOUNTS,a);tnffmInvalidate_();return ok_({message:'Password changed successfully.'});}
function tnffmResetPassword_(p){var u=String(p.username||'').trim().toLowerCase(),email=String(p.email||'').trim().toLowerCase(),a=tnffmAccountRows_(),x=a.find(function(v){return String(v.username||'').toLowerCase()===u&&String(v.email||'').toLowerCase()===email;});if(!x)throw new Error('Username and registered email do not match.');x.passwordHash=String(p.passwordHash||'');x.updatedAt=new Date().toISOString();writeGeneric_(TABS.ACCOUNTS,a);tnffmInvalidate_();return ok_({message:'Password reset successfully.'});}
function tnffmGetSubmissions_(p){var slug=String(p.teamSlug||''),u=String(p.username||'').toLowerCase();return ok_({submissions:tnffmSection_(TABS.SUBMISSIONS).filter(function(x){return String(x.teamSlug||'')===slug&&(!u||String(x.username||'').toLowerCase()===u);})});}
function tnffmSubmit_(p){var rows=tnffmSection_(TABS.SUBMISSIONS),id='SUB-'+Date.now();rows.push({submissionId:id,username:String(p.username||''),teamSlug:String(p.teamSlug||''),team:String(p.team||p.teamSlug||''),tournamentName:String(p.tournamentName||''),tournamentDate:String(p.tournamentDate||''),organizerName:String(p.organizerName||''),prizePool:String(p.prizePool||''),finalPosition:Number(p.finalPosition||0),finalLeaderboard:String(p.finalLeaderboard||''),proofUrl:String(p.proofUrl||''),status:'Pending',reviewNotes:'',reviewedBy:'',reviewedAt:'',createdAt:new Date().toISOString()});writeGeneric_(TABS.SUBMISSIONS,rows);tnffmInvalidate_();return ok_({saved:true,submissionId:id,message:'Tournament result submitted successfully.'});}
function tnffmFeedback_(p){var rows=tnffmSection_(TABS.FEEDBACK),id=String(p.feedbackId||'FB-'+Date.now());rows.push({feedbackId:id,timestamp:String(p.timestamp||new Date().toISOString()),team:String(p.teamName||''),teamSlug:String(p.teamSlug||''),username:String(p.username||''),type:String(p.type||'Other'),message:String(p.message||''),status:String(p.status||'New'),adminReply:'',updatedAt:new Date().toISOString()});writeGeneric_(TABS.FEEDBACK,rows);tnffmInvalidate_();return ok_({message:'Feedback saved to Google Sheets.',feedbackId:id});}
function tnffmListFeedback_(){return ok_({feedback:tnffmSection_(TABS.FEEDBACK).reverse()});}
function tnffmUpdateFeedback_(p){var rows=tnffmSection_(TABS.FEEDBACK),x=rows.find(function(v){return String(v.feedbackId||'')===String(p.feedbackId||'');});if(!x)throw new Error('Feedback not found.');var status=String(p.status||'');if(['New','Reviewing','Resolved'].indexOf(status)<0)throw new Error('Invalid feedback status.');x.status=status;x.updatedAt=new Date().toISOString();writeGeneric_(TABS.FEEDBACK,rows);tnffmInvalidate_();return ok_({message:'Feedback status updated.'});}
function doGet(e){try{return ok_(tnffmCachedGet_());}catch(x){console.error(err_(x));return fail_(err_(x),'READ_FAILED');}}
function doPost(e){var lock=LockService.getScriptLock();try{if(!e||!e.postData||!e.postData.contents)return fail_('Empty request body.','EMPTY_BODY');if(e.postData.contents.length>15000000)return fail_('Request is too large.','BODY_TOO_LARGE');var p=JSON.parse(e.postData.contents||'{}');if(p.action==='health'||p.action==='healthCheck')return healthCheck();if(p.action==='setup'||p.action==='setupSheets')return setupTNFFM();if(p.action==='loginTeam')return tnffmLogin_(p);if(p.action==='registerTeam')return tnffmRegisterTeam_(p);if(p.action==='changeTeamPassword')return tnffmChangePassword_(p);if(p.action==='resetTeamPassword')return tnffmResetPassword_(p);if(p.action==='getTeamSubmissions')return tnffmGetSubmissions_(p);if(p.action==='submitFinalLeaderboard')return tnffmSubmit_(p);if(p.action==='submitFeedback')return tnffmFeedback_(p);if(p.action==='listFeedback')return tnffmListFeedback_();if(p.action==='updateFeedbackStatus')return tnffmUpdateFeedback_(p);if(p.action==='uploadLogo')return ok_({url:uploadLogo_(p.dataUrl,p.fileName)});var inc=incoming_(p),sections=Object.keys(inc);if(!sections.length)return fail_('No supported data section was supplied.','NO_SECTIONS');lock.waitLock(25000);sections.forEach(function(s){writeOne_(s,inc[s]);});SpreadsheetApp.flush();tnffmInvalidate_();var fresh=tnffmReadAll_(),verification={};sections.forEach(function(s){verification[s]=verify_(s,inc[s],fresh[s]);});return ok_({saved:true,verified:true,savedSections:sections,savedAt:new Date().toISOString(),verification:verification,data:fresh});}catch(x){console.error(err_(x));return fail_(err_(x),'WRITE_FAILED');}finally{try{lock.releaseLock();}catch(z){}}}
