import { NextRequest, NextResponse } from "next/server";
import { revalidatePath, revalidateTag } from "next/cache";
import crypto from "node:crypto";
import { clearSheetPayloadCache } from "@/lib/sheet-cache";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const text = (v: unknown) => String(v ?? "").trim();
const REQUEST_TIMEOUT_MS = 20_000;
function safeEqual(left: string, right: string) { const a=Buffer.from(left,"utf8"),b=Buffer.from(right,"utf8"); return a.length===b.length&&crypto.timingSafeEqual(a,b); }
function validateEvents(events:any[]) {
  if(events.length>5000) throw new Error("Events exceeds the supported limit."); const ids=new Set<string>();
  for(const event of events){ const name=text(event?.name??event?.Name??event?.eventName); if(!name) throw new Error("Every tournament announcement must have a name."); const id=text(event?.id??event?.eventId??event?.["Event ID"]); if(id){if(ids.has(id))throw new Error(`Duplicate event ID: ${id}`);ids.add(id);}
    if(event?.published===true){const matches=Number(event?.matchesPlayed??event?.["Matches Played"]??0);if(!Number.isFinite(matches)||matches<=0)throw new Error(`${name}: Matches Played must be greater than 0 before publishing.`);const prize=Number(String(event?.prize??event?.prizePool??"").replace(/[^0-9.]/g,""))||0;const status=text(event?.status).toLowerCase();if(prize<=1000&&status!=="official")throw new Error(`${name}: prize pool must be above Rs.1000 before publishing.`);const results=Array.isArray(event?.results)?event.results.filter((r:any)=>text(r?.teamName??r?.["Team Name"]??r?.team)):[];if(!results.length)throw new Error(`${name}: add at least one result before publishing.`);const names=new Set<string>(),ranks=new Set<number>();for(const result of results){const team=text(result?.teamName??result?.["Team Name"]??result?.team).toLowerCase();if(names.has(team))throw new Error(`${name}: duplicate teams are not allowed.`);names.add(team);const rank=Number(result?.rank??result?.position??result?.Position??0);if(!Number.isInteger(rank)||rank<1||rank>18||ranks.has(rank))throw new Error(`${name}: ranks must be unique integers from 1 to 18.`);ranks.add(rank);}}
  }
}
function validateAchievements(items:any[]) { if(items.length>5000) throw new Error("Achievements exceeds the supported limit."); const ids=new Set<string>(); for(const item of items){ const id=text(item?.id??item?.ID); const title=text(item?.title??item?.Title); if(!title) throw new Error("Every achievement must have a title."); if(id){if(ids.has(id))throw new Error(`Duplicate achievement ID: ${id}`);ids.add(id);} const image=text(item?.imageUrl??item?.ImageURL??item?.["Image URL"]); if(image){try{const u=new URL(image);if(!["http:","https:"].includes(u.protocol))throw new Error();}catch{throw new Error(`${title}: image URL must be http(s).`);}} } }
async function callSheets(url:string,method:"GET"|"POST",body?:unknown){let target:URL;try{target=new URL(url);}catch{throw new Error("GOOGLE_SHEETS_WEBHOOK_URL is not a valid URL.");}if(!/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec\/?$/i.test(target.origin+target.pathname))throw new Error("GOOGLE_SHEETS_WEBHOOK_URL must be the current deployed Google Apps Script Web App /exec URL.");const requestId=`${Date.now()}-${Math.random().toString(36).slice(2)}`;target.searchParams.set("_tnffm_request",requestId);const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const response=await fetch(target.toString(),{method,cache:"no-store",headers:{Accept:"application/json","Cache-Control":"no-cache, no-store, max-age=0",Pragma:"no-cache","X-TNFFM-Request-ID":requestId,...(method==="POST"?{"Content-Type":"application/json"}:{})},...(method==="POST"?{body:JSON.stringify(body??{})}:{}),signal:controller.signal});const raw=await response.text();let data:any=null;try{data=raw?JSON.parse(raw):null;}catch{}if(!response.ok){if(response.status===404)throw new Error("Google Apps Script HTTP 404. The configured Web App deployment is missing, deleted, or outdated.");throw new Error(`Google Apps Script HTTP error (${response.status}). ${text(data?.message||data?.error||raw).slice(0,500)}`);}if(!data||data.ok===false)throw new Error(`Google Sheet request failed. ${text(data?.message||data?.error||raw||"Apps Script returned an invalid response.").slice(0,500)}`);return data;}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new Error(`Google Apps Script request timed out after ${REQUEST_TIMEOUT_MS/1000} seconds. Check the Web App deployment and Spreadsheet ID.`);throw error;}finally{clearTimeout(timeout);}}
function keyOf(value:unknown){return text(value)}
function teamIdOf(t:any){return keyOf(t?.teamId??t?.["Team ID"])} function teamNameOf(t:any){return keyOf(t?.teamName??t?.["Team Name"]??t?.Team)}
function rankingKey(r:any){return keyOf(r?.teamId??r?.["Team ID"])||`name:${keyOf(r?.teamName??r?.["Team Name"]??r?.Team).toLowerCase()}`}
function collaboratorKey(c:any){return keyOf(c?.collaboratorId??c?.id??c?.["Collaborator ID"])||`name:${keyOf(c?.name??c?.Name).toLowerCase()}`}
function resultKey(r:any){return keyOf(r?.resultId??r?.id??r?.["Result ID"])} function eventKey(e:any){return keyOf(e?.eventId??e?.id??e?.["Event ID"])}
function simpleKey(item:any,names:string[]){for(const name of names){const value=keyOf(item?.[name]);if(value)return value;}return ""}
function achievementKey(a:any){return keyOf(a?.id??a?.ID)}
function verifyKeys(expected:any[],actual:any[],name:string,key:(v:any)=>string){if(!Array.isArray(actual))throw new Error(`${name}: Google Sheets did not return a valid array.`);const expectedKeys=expected.map(key).filter(Boolean),actualKeys=new Set(actual.map(key).filter(Boolean));const missing=expectedKeys.filter(k=>!actualKeys.has(k));if(missing.length)throw new Error(`${name} was written but read-back does not match. Missing record: ${missing[0]}`);}
function verifyTeams(expected:any[],actual:any[]){if(!Array.isArray(actual))throw new Error("Teams: Google Sheets did not return a valid array.");const ids=new Set(actual.map(teamIdOf).filter(Boolean).map(v=>v.toLowerCase())),names=new Set(actual.map(teamNameOf).filter(Boolean).map(v=>v.toLowerCase()));for(const team of expected){const id=teamIdOf(team).toLowerCase(),name=teamNameOf(team).toLowerCase();if(!id&&!name)continue;if(id?(ids.has(id)||names.has(name)):names.has(name))continue;throw new Error(`Teams was written but read-back does not match. Missing record: ${id}|${name}`);}}
export async function POST(request:NextRequest){try{const payload=await request.json();const configuredPassword=process.env.ADMIN_PASSWORD;if(!configuredPassword||!safeEqual(String(payload?.password??""),configuredPassword))return NextResponse.json({ok:false,message:"Invalid password."},{status:401,headers:{"Cache-Control":"no-store"}});const url=process.env.GOOGLE_SHEETS_WEBHOOK_URL?.trim();if(!url)return NextResponse.json({ok:false,message:"GOOGLE_SHEETS_WEBHOOK_URL is not configured."},{status:503,headers:{"Cache-Control":"no-store"}});
  const data:Record<string,any[]>={}; for(const key of ["teams","rankings","events","rankingResults","results","news","achievements","collaborators","accounts","submissions","feedback"]){if(Array.isArray(payload?.[key]))data[key]=payload[key];}
  if(!Object.keys(data).length)return NextResponse.json({ok:false,message:"No supported data section was supplied."},{status:400,headers:{"Cache-Control":"no-store"}});if(Array.isArray(data.events))validateEvents(data.events);if(Array.isArray(data.achievements))validateAchievements(data.achievements);
  const saved=await callSheets(url,"POST",data);if(saved?.verified===false||saved?.saved===false)throw new Error(text(saved?.message||saved?.error||"Google Apps Script did not confirm the write."));const fresh=await callSheets(url,"GET");
  if(Array.isArray(data.teams))verifyTeams(data.teams,fresh.teams);if(Array.isArray(data.rankings))verifyKeys(data.rankings,fresh.rankings,"Rankings",rankingKey);if(Array.isArray(data.collaborators))verifyKeys(data.collaborators,fresh.collaborators,"Collaborators",collaboratorKey);if(Array.isArray(data.news))verifyKeys(data.news,fresh.news,"News",x=>simpleKey(x,["ID","id"]));if(Array.isArray(data.achievements))verifyKeys(data.achievements,fresh.achievements,"Achievements",achievementKey);if(Array.isArray(data.events))verifyKeys(data.events,fresh.events,"Events",eventKey);if(Array.isArray(data.rankingResults)||Array.isArray(data.results))verifyKeys(data.rankingResults||data.results,fresh.rankingResults||fresh.results,"Event Results",resultKey);if(Array.isArray(data.accounts))verifyKeys(data.accounts,fresh.accounts,"Team Accounts",x=>simpleKey(x,["Username","username"]));if(Array.isArray(data.submissions))verifyKeys(data.submissions,fresh.submissions,"Submissions",x=>simpleKey(x,["SubmissionID","submissionId"]));if(Array.isArray(data.feedback))verifyKeys(data.feedback,fresh.feedback,"Feedback",x=>simpleKey(x,["FeedbackID","feedbackId"]));
  clearSheetPayloadCache();try{revalidateTag("tnffm-sheet");}catch{} for(const path of ["/","/ranking","/teams","/tracked-events","/tournament-announcements","/achievement-showcase","/admin","/admin/tournament-announcements","/admin/achievement-showcase","/collaborators","/news"]){try{revalidatePath(path);}catch{}}
  return NextResponse.json({...saved,ok:true,saved:true,verified:true,googleSheets:true,readBackVerified:true},{headers:{"Cache-Control":"no-store"}});
}catch(error){console.error("Admin Google Sheets save error:",error);return NextResponse.json({ok:false,saved:false,verified:false,readBackVerified:false,message:error instanceof Error?error.message:"Google Sheet update failed."},{status:502,headers:{"Cache-Control":"no-store"}})}}
