"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ChevronDown, HelpCircle, MessageCircle } from "lucide-react";
const faq=[
["How does TNFFM ranking work?","Eligible and verified tournament results are included in the community ranking using the published TNFFM point system."],
["How do I submit a tournament?","Open My Submissions, enter the complete event information and attach clear final-result proof. Review the Before You Submit checklist first."],
["Why was my submission rejected?","A submission may require correction when required information is missing, proof is unclear, the event is ineligible, or the result cannot be verified."],
["How do I update my team profile?","Use Team Profile in the dashboard. Signed-in team accounts can update supported profile and roster information and save the changes."],
["How are results verified?","TNFFM reviews the submitted event details and supporting proof before an eligible result is added to the official ranking."],
["How can I dispute a result?","Contact TNFFM support with the event details, the disputed result and supporting evidence so the team can request a review."],
];
export default function HelpPage(){const[open,setOpen]=useState(0);return <main className="min-h-screen bg-[#050507] px-3 py-5 text-white sm:px-6 sm:py-8"><div className="mx-auto max-w-4xl"><Link href="/team-dashboard" className="mb-5 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-gold"><ArrowLeft className="h-4 w-4"/> Back to Team Dashboard</Link><header className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#151518] to-[#09090b] p-6 sm:p-9"><div className="flex gap-4"><div className="rounded-2xl border border-gold/25 bg-gold/10 p-3 text-gold"><HelpCircle className="h-7 w-7"/></div><div><p className="text-[11px] font-bold uppercase tracking-[.24em] text-gold">TNFFM Support</p><h1 className="font-rajdhani text-4xl font-bold uppercase sm:text-5xl">Help / FAQ</h1><p className="mt-2 text-sm text-slate-400">Quick answers for teams, submissions, rankings and account management.</p></div></div></header><section className="mt-5 rounded-3xl border border-white/10 bg-white/[.02] p-4 sm:p-6"><div className="space-y-2">{faq.map(([q,a],i)=><div className="overflow-hidden rounded-2xl border border-white/10 bg-black/20" key={q}><button onClick={()=>setOpen(open===i?-1:i)} className="flex min-h-14 w-full items-center justify-between px-4 text-left font-semibold"><span>{q}</span><ChevronDown className={`h-5 w-5 text-gold transition-transform ${open===i?'rotate-180':''}`}/></button>{open===i&&<p className="border-t border-white/10 px-4 py-4 text-sm leading-6 text-slate-400">{a}</p>}</div>)}</div></section><Link href="/team-dashboard/feedback" className="mt-5 flex items-center gap-3 rounded-2xl border border-gold/20 bg-gold/[.04] p-5 hover:border-gold/40"><MessageCircle className="h-5 w-5 text-gold"/><div><b>Still need help?</b><p className="text-sm text-slate-500">Send feedback or contact TNFFM support.</p></div></Link></div></main>}
