/** TNFFM Google Sheets backend - canonical publishing/storage API. */
const CONFIG={sheets:{teams:'Teams',rankings:'Community Rankings',events:'Events',rankingResults:'Ranking Results',collaborators:'Collaborators',news:'News'},maxRows:5000,maxBodyChars:15000000};
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function ok_(x){return json_(Object.assign({ok:true},x||{}))}
function error_(x){return json_({ok:false,message:String(x||'Unknown Google Sheets error.')})}
function doGet(){try{return ok_(readAll_())}catch(e){console.error(e);return error_(e.message||e)}}
function doPost(e){var lock=LockService.getScriptLock();try{if(!e||!e.postData||!e.postData.contents)return error_('Empty request body.');if(e.postData.contents.length>CONFIG.maxBodyChars)throw new Error('Request is too large.');lock.waitLock(30000);var p=JSON.parse(e.postData.contents);if(p.action==='uploadLogo')return ok_({url:uploadLogo_(p.dataUrl,p.fileName)});var keys=[['teams','teams'],['rankings','rankings'],['events','events'],['rankingResults','rankingResults'],['collaborators','collaborators'],['news','news']];var changed=[];keys.forEach(function(pair){var k=pair[0];if(Object.prototype.hasOwnProperty.call(p,k)){if(!Array.isArray(p[k]))throw new Error(k+' must be an array.');writeSection_(CONFIG.sheets[pair[1]],p[k]);changed.push(k)}});if(!changed.length)throw new Error('No supported data section was supplied.');SpreadsheetApp.flush();var fresh=readAll_();var verification={};changed.forEach(function(k){var expected=p[k].length,actual=Array.isArray(fresh[k])?fresh[k].length:0;verification[k]={expected:expected,actual:actual,match:expected===actual};if(expected!==actual)throw new Error(k+' write verification failed. Expected '+expected+', received '+actual+'.')});return ok_({savedSections:changed,savedAt:new Date().toISOString(),verified:true,verification:verification,data:fresh})}catch(e){console.error(e);return error_(e.message||e)}finally{try{lock.releaseLock()}catch(_){} }}
function readAll_(){var rr=readSection_(CONFIG.sheets.rankingResults);return{teams:readSection_(CONFIG.sheets.teams),rankings:readSection_(CONFIG.sheets.rankings),events:readSection_(CONFIG.sheets.events),rankingResults:rr,results:rr,collaborators:readSection_(CONFIG.sheets.collaborators),news:readSection_(CONFIG.sheets.news),serverTime:new Date().toISOString()}}
function getSpreadsheet_(){var id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(id){try{return SpreadsheetApp.openById(id)}catch(e){throw new Error('Configured SPREADSHEET_ID could not be opened: '+e.message)}}return SpreadsheetApp.getActiveSpreadsheet()}
function getOrCreateSheet_(name){var ss=getSpreadsheet_(),s=ss.getSheetByName(name);return s||ss.insertSheet(name)}
function cleanHeader_(v){return String(v==null?'':v).trim()}
function readSection_(name){var s=getSpreadsheet_().getSheetByName(name);if(!s||s.getLastRow()<1||s.getLastColumn()<1)return[];var lr=Math.min(s.getLastRow(),CONFIG.maxRows),lc=s.getLastColumn(),v=s.getRange(1,1,lr,lc).getDisplayValues(),h=v[0].map(cleanHeader_);if(!h.some(Boolean))return[];return v.slice(1).filter(function(r){return r.some(function(x){return String(x).trim()!==''})}).map(function(r){var o={};h.forEach(function(k,i){if(k)o[k]=decodeCell_(r[i])});return normalizeReadObject_(o)})}
function decodeCell_(v){var x=String(v==null?'':v).trim();if(!x)return'';if((x[0]==='['&&x[x.length-1]===']')||(x[0]==='{'&&x[x.length-1]==='}')){try{return JSON.parse(x)}catch(_){} }if(/^(true|false)$/i.test(x))return x.toLowerCase()==='true';return String(v==null?'':v)}
function normalizeReadObject_(o){var out=Object.assign({},o);Object.keys(o).forEach(function(k){var c=canonicalKey_(k);if(c&&!Object.prototype.hasOwnProperty.call(out,c))out[c]=o[k]});return out}
function canonicalKey_(k){var m={'Team':'teamName','Team Name':'teamName','team':'teamName','Slug':'slug','Team ID':'teamId','TeamId':'teamId','Rank':'rank','PreviousRank':'previousRank','Previous Rank':'previousRank','CommunityPoints':'communityPoints','Community Score':'communityScore','CommunityScore':'communityScore','Badge':'badge','Logo URL':'logoUrl','LogoURL':'logoUrl','Banner URL':'bannerUrl','BannerURL':'bannerUrl','Kills':'kills','Booyahs':'booyahs','MatchesPlayed':'matchesPlayed','Matches Played':'matchesPlayed','Championships':'championships','RunnerUp':'runnerUp','Runner-Up':'runnerUp','SecondRunnerUp':'secondRunnerUp','2nd Runner-Up':'secondRunnerUp','Top5Finishes':'top5Finishes','Top 5 Finishes':'top5Finishes','FinalistFinishes':'finalistFinishes','OfficialMatchFinalists':'officialMatchFinalists','EventsPlayed':'eventsPlayed','GrandFinals':'grandFinals','PositionPoints':'positionPoints','TotalPoints':'totalPoints','Players':'players','Status':'status','RegistrationStatus':'registrationStatus','Description':'description','Mobile Number':'mobileNumber','LastUpdated':'lastUpdated','Last Updated':'lastUpdated','WinRate':'winRate','KillRatio':'killRatio','BooyahRatio':'booyahRatio','Event ID':'eventId','EventId':'eventId','Name':'name','Event Name':'name','Organizer':'organizer','Teams':'teams','Team Count':'teams','Prize':'prize','Prize Pool':'prize','Date':'date','Event Date':'date','Notes':'notes','Counted':'counted','Published':'published','Results':'results','ID':'id','Title':'title','Type':'type','ImageURL':'imageUrl','Link':'link','Result ID':'resultId','ResultId':'resultId','Position':'position','Total':'total','Kill Points':'killPoints','Proof URL':'proofUrl','Verified':'verified'};return m[k]||k}
function writeSection_(name,items){var s=getOrCreateSheet_(name),normalized=items.map(function(x){return sanitizeForSheet_(x||{})}),headers=[];if(s.getLastColumn()>0&&s.getLastRow()>0)headers=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0].map(cleanHeader_).filter(Boolean);var seen={};headers.forEach(function(h){seen[h]=true});normalized.forEach(function(x){Object.keys(x).forEach(function(k){if(!seen[k]){headers.push(k);seen[k]=true}})});if(!headers.length)headers=['id'];if(headers.length>100)throw new Error(name+' has too many columns.');var rows=normalized.map(function(x){return headers.map(function(h){return x[h]==null?'':x[h]})}),rr=Math.max(1,rows.length+1),cc=headers.length;if(s.getMaxRows()<rr)s.insertRowsAfter(s.getMaxRows(),rr-s.getMaxRows());if(s.getMaxColumns()<cc)s.insertColumnsAfter(s.getMaxColumns(),cc-s.getMaxColumns());var clearRows=Math.max(s.getLastRow(),rr),clearCols=Math.max(s.getLastColumn(),cc);if(clearRows&&clearCols)s.getRange(1,1,clearRows,clearCols).clearContent();s.getRange(1,1,1,cc).setValues([headers]);if(rows.length)s.getRange(2,1,rows.length,cc).setValues(rows);s.setFrozenRows(1);SpreadsheetApp.flush()}
function sanitizeForSheet_(o){var out={};Object.keys(o).forEach(function(k){if(!k||k==='undefined'||k==='null')return;var v=o[k];if(v==null)v='';if(typeof v==='object')v=JSON.stringify(v);if(typeof v==='boolean')v=v?'true':'false';if(typeof v==='string'&&/^[=+\-@]/.test(v))v="'"+v;out[String(k)]=v});return out}
function uploadLogo_(dataUrl,fileName){if(typeof dataUrl!=='string'||dataUrl.indexOf('data:image/')!==0)throw new Error('Invalid image data.');if(dataUrl.length>4000000)throw new Error('Image is too large.');var m=dataUrl.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!m)throw new Error('Invalid image format.');var blob=Utilities.newBlob(Utilities.base64Decode(m[2]),m[1],String(fileName||'tnffm-image').replace(/[^a-zA-Z0-9._-]/g,'-')),id=PropertiesService.getScriptProperties().getProperty('DRIVE_FOLDER_ID'),folder=id?DriveApp.getFolderById(id):DriveApp.getRootFolder(),file=folder.createFile(blob);file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return'https://drive.google.com/uc?export=view&id='+file.getId()}
function setupSheets(){Object.keys(CONFIG.sheets).forEach(function(k){getOrCreateSheet_(CONFIG.sheets[k])});SpreadsheetApp.flush()}
function setupTNFFM(){setupSheets()}
function setSpreadsheetId(id){if(!id)throw new Error('Spreadsheet ID required.');SpreadsheetApp.openById(String(id));PropertiesService.getScriptProperties().setProperty('SPREADSHEET_ID',String(id));return ok_({spreadsheetId:String(id),message:'TNFFM spreadsheet configured.'})}
