/* TNFFM — CLEAN GOOGLE SHEETS BACKEND
 * Use this script with a NEW Google Spreadsheet.
 * 1) Set Script Property: SPREADSHEET_ID = your new spreadsheet ID.
 * 2) Run setupTNFFM() once from the Apps Script editor.
 * 3) Deploy as Web app: Execute as Me, Who has access: Anyone.
 * 4) Put the deployed /exec URL in Vercel as GOOGLE_SHEETS_WEBHOOK_URL.
 *
 * Important separation:
 * Teams + Team Rosters      -> community teams
 * Community Rankings        -> official ranking snapshot (formula owned by the website/admin workflow)
 * Events + Event Results    -> tracked/ranking events
 * Tournament Announcements -> promotional tournaments (independent from results/rankings)
 * TournamentNews            -> news
 * Community Achievements    -> achievement showcase (independent from news/rankings)
 */
var VERSION='TNFFM-2026.09.09-CLEAN-1',MAX_ROWS=5000,MAX_BODY_CHARS=15000000;
var TABS={TEAMS:'Teams',ROSTERS:'Team Rosters',RANKINGS:'Community Rankings',EVENTS:'Events',RESULTS:'Event Results',ANNOUNCEMENTS:'Tournament Announcements',NEWS:'TournamentNews',ACHIEVEMENTS:'Community Achievements',COLLAB:'Collaborators',ACCOUNTS:'TeamAccounts',SUBMISSIONS:'Submissions',FEEDBACK:'Feedback'};
var HEADERS={};
HEADERS[TABS.TEAMS]=['Team ID','Team Name','Slug','Logo URL','Banner URL','Description','Mobile Number','Status','Registration Status','Created At','Updated At'];
HEADERS[TABS.ROSTERS]=['Player ID','Team ID','Team Name','Player Name','UID','Role','Player Logo URL','Status','Created At','Updated At'];
HEADERS[TABS.RANKINGS]=['Rank','Team ID','Team Name','Slug','Events Played','Championships','Runner-Up','2nd Runner-Up','Top 5 Finishes','Community Score','Kills','Booyahs','Kill Ratio','Booyah Ratio','Position Points','Total Points','Matches Played','Grand Finals','Win Rate','Eligible','Status','Updated At'];
HEADERS[TABS.EVENTS]=['Event ID','Name','Organizer','Organizer URL','Registration URL','Teams','Total Slots','Registered Slots','Prize','Status','Stage','Counted','Date','Notes','Matches Played','Published','Results','Created At','Updated At'];
HEADERS[TABS.RESULTS]=['Result ID','Event ID','Event Name','Team ID','Team Name','Position','Kills','Booyahs','Position Points','Kill Points','Total Points','Proof URL','Verified','Updated At'];
HEADERS[TABS.ANNOUNCEMENTS]=['Announcement ID','Tournament Name','Organization Name','Organization URL','Registration URL','Tournament Date','Prize Pool','Total Slots','Registered Slots','Stage','Status','Description','Published','Created At','Updated At'];
HEADERS[TABS.NEWS]=['ID','Title','Description','Date','Type','Status','ImageURL','Link','UpdatedAt'];
HEADERS[TABS.ACHIEVEMENTS]=['ID','Title','Description','Date','Status','ImageURL','Link','UpdatedAt'];
HEADERS[TABS.COLLAB]=['Collaborator ID','Name','Role','Status','Contact','LogoURL','Website','Instagram','UpdatedAt'];
HEADERS[TABS.ACCOUNTS]=['Username','PasswordHash','TeamSlug','Email','Status','CreatedAt','UpdatedAt'];
HEADERS[TABS.SUBMISSIONS]=['SubmissionID','Username','TeamSlug','Team','TournamentName','TournamentDate','OrganizerName','PrizePool','FinalPosition','FinalLeaderboard','ProofURL','Status','ReviewNotes','ReviewedBy','ReviewedAt','CreatedAt'];
HEADERS[TABS.FEEDBACK]=['FeedbackID','Username','TeamSlug','Team','Message','Status','AdminReply','CreatedAt','UpdatedAt'];
function clean_(v){return v==null?'':String(v).trim()}
function now_(){return new Date().toISOString()}
function num_(v){var n=Number(v);return isFinite(n)?n:0}
function int_(v){return Math.max(0,Math.floor(num_(v)))}
function bool_(v){if(v===true)return true;var x=clean_(v).toLowerCase();return x==='true'||x==='yes'||x==='1'||x==='published'||x==='active'}
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function ok_(x){var o={ok:true,version:VERSION};if(x)Object.keys(x).forEach(function(k){o[k]=x[k]});return json_(o)}
function fail_(m,c){return json_({ok:false,version:VERSION,code:c||'TNFFM_ERROR',message:clean_(m)||'Unknown error'})}
function err_(e){return e&&e.message?e.message:String(e||'Unknown error')}
function prop_(o,keys){for(var i=0;i<keys.length;i++)if(o&&o[keys[i]]!==undefined&&o[keys[i]]!==null)return o[keys[i]];return''}
function slug_(v){var s=clean_(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,45);return s||'team'}
function id_(prefix){return prefix+'-'+Date.now()+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,10).toUpperCase()}
var SS_=null;
function getSS_(){if(SS_)return SS_;var id=clean_(PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID'));if(id){SS_=SpreadsheetApp.openById(id);return SS_}var active=SpreadsheetApp.getActiveSpreadsheet();if(active){SS_=active;return SS_}throw new Error('SPREADSHEET_ID is not configured.')}
function sheet_(name){var s=getSS_().getSheetByName(name);return s||getSS_().insertSheet(name)}
function ensure_(s,h){if(s.getMaxColumns()<h.length)s.insertColumnsAfter(s.getMaxColumns(),h.length-s.getMaxColumns());var existing=s.getRange(1,1,1,h.length).getDisplayValues()[0];var same=true;for(var i=0;i<h.length;i++)if(clean_(existing[i])!==h[i]){same=false;break}if(!same)s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1)}
function ensureAll_(){Object.keys(HEADERS).forEach(function(k){ensure_(sheet_(k),HEADERS[k])});SpreadsheetApp.flush()}
function setupTNFFM(){ensureAll_();return ok_({message:'TNFFM Google Sheet structure is ready.',tabs:Object.keys(HEADERS).map(function(k){return HEADERS[k]&&k})})}
function setupSheets(){return setupTNFFM()}
function parse_(v){var x=clean_(v);if(!x)return'';if((x[0]==='['&&x[x.length-1]===']')||(x[0]==='{'&&x[x.length-1]==='}'))try{return JSON.parse(x)}catch(e){}if(/^(true|false)$/i.test(x))return x.toLowerCase()==='true';return x}
function canon_(k){var m={'Team ID':'teamId','Team Name':'teamName','Team':'teamName','Slug':'slug','Logo URL':'logoUrl','LogoURL':'logoUrl','Banner URL':'bannerUrl','Description':'description','Mobile Number':'mobileNumber','Status':'status','Registration Status':'registrationStatus','Created At':'createdAt','CreatedAt':'createdAt','Updated At':'updatedAt','UpdatedAt':'updatedAt','Player ID':'playerId','Player Name':'playerName','UID':'uid','Role':'role','Player Logo URL':'playerLogoUrl','Rank':'rank','Events Played':'eventsPlayed','Championships':'championships','Runner-Up':'runnerUp','2nd Runner-Up':'secondRunnerUp','Top 5 Finishes':'top5Finishes','Community Score':'communityScore','Kills':'kills','Booyahs':'booyahs','Kill Ratio':'killRatio','Booyah Ratio':'booyahRatio','Position Points':'positionPoints','Total Points':'totalPoints','Matches Played':'matchesPlayed','Grand Finals':'grandFinals','Win Rate':'winRate','Eligible':'eligible','Event ID':'eventId','EventId':'eventId','Name':'name','Event Name':'eventName','Organizer':'organizer','Organizer URL':'organizerUrl','Registration URL':'registrationUrl','Teams':'teams','Total Slots':'totalSlots','Registered Slots':'registeredSlots','Prize':'prize','Prize Pool':'prizePool','Date':'date','Event Date':'date','Notes':'notes','Stage':'stage','Counted':'counted','Published':'published','Results':'results','Announcement ID':'announcementId','Tournament Name':'tournamentName','Organization Name':'organizationName','Organization URL':'organizationUrl','Tournament Date':'tournamentDate','ID':'id','Title':'title','Type':'type','ImageURL':'imageUrl','Image URL':'imageUrl','Link':'link','Result ID':'resultId','Position':'position','Kill Points':'killPoints','Total':'total','Proof URL':'proofUrl','ProofURL':'proofUrl','Verified':'verified','Username':'username','PasswordHash':'passwordHash','TeamSlug':'teamSlug','Email':'email','SubmissionID':'submissionId','TournamentName':'tournamentName','TournamentDate':'tournamentDate','OrganizerName':'organizerName','FinalPosition':'finalPosition','FinalLeaderboard':'finalLeaderboard','ReviewNotes':'reviewNotes','ReviewedBy':'reviewedBy','ReviewedAt':'reviewedAt','FeedbackID':'feedbackId','Message':'message','AdminReply':'adminReply','Contact':'contact','Website':'website','Instagram':'instagram','Collaborator ID':'collaboratorId'};return m[k]||k}
function read_(name){var s=sheet_(name),lr=s.getLastRow(),lc=s.getLastColumn();if(lr<2||lc<1)return[];var h=s.getRange(1,1,1,lc).getDisplayValues()[0].map(clean_),rows=s.getRange(2,1,Math.min(lr-1,MAX_ROWS-1),lc).getDisplayValues(),out=[];rows.forEach(function(r){if(!r.some(function(v){return clean_(v)!==''}))return;var o={};h.forEach(function(k,i){if(!k)return;var v=parse_(r[i]);o[k]=v;var c=canon_(k);if(o[c]===undefined)o[c]=v});out.push(o)});return out}
function cell_(v){if(v==null)return'';if(typeof v==='object')v=JSON.stringify(v);if(typeof v==='boolean')v=v?'true':'false';var x=String(v);return/^[=+\-@]/.test(x)?"'"+x:x}
function write_(name,items){if(!Array.isArray(items))throw new Error(name+' must be an array.');if(items.length>MAX_ROWS-1)throw new Error(name+' exceeds '+(MAX_ROWS-1)+' data rows.');var s=sheet_(name),h=HEADERS[name],last=s.getLastRow();if(last>1)s.getRange(2,1,last-1,h.length).clearContent();if(!items.length){SpreadsheetApp.flush();return}var rows=items.map(function(x){return h.map(function(k){var v=x[k];if(v===undefined)v=x[canon_(k)];return cell_(v)})});s.getRange(2,1,rows.length,h.length).setValues(rows);SpreadsheetApp.flush()}
function rosterMap_(){var m={};read_(TABS.ROSTERS).forEach(function(p){var id=clean_(prop_(p,['teamId','Team ID']));if(!id)return;(m[id]||(m[id]=[])).push({playerId:clean_(prop_(p,['playerId','Player ID'])),name:clean_(prop_(p,['playerName','Player Name'])),uid:clean_(prop_(p,['uid','UID'])),role:clean_(prop_(p,['role','Role'])),playerLogoUrl:clean_(prop_(p,['playerLogoUrl','Player Logo URL'])),status:clean_(prop_(p,['status','Status']))||'Active',createdAt:clean_(prop_(p,['createdAt','Created At'])),updatedAt:clean_(prop_(p,['updatedAt','Updated At']))})});return m}
function readTeams_(){var rm=rosterMap_();return read_(TABS.TEAMS).map(function(t){var id=clean_(prop_(t,['teamId','Team ID'])),name=clean_(prop_(t,['teamName','Team Name','Team']));return{teamId:id,teamName:name,slug:clean_(prop_(t,['slug','Slug']))||slug_(name),logoUrl:clean_(prop_(t,['logoUrl','Logo URL','LogoURL'])),bannerUrl:clean_(prop_(t,['bannerUrl','Banner URL'])),description:clean_(prop_(t,['description','Description'])),mobileNumber:clean_(prop_(t,['mobileNumber','Mobile Number'])),status:clean_(prop_(t,['status','Status']))||'Active',registrationStatus:clean_(prop_(t,['registrationStatus','Registration Status']))||'Registered',players:(rm[id]||[]).length,roster:rm[id]||[],createdAt:clean_(prop_(t,['createdAt','Created At'])),lastUpdated:clean_(prop_(t,['updatedAt','Updated At']))};}).filter(function(t){return!!t.teamName})}
function resultRowsForEvents_(events){var out=[];events.forEach(function(e){var eid=clean_(prop_(e,['eventId','Event ID','id'])),en=clean_(prop_(e,['name','eventName','Event Name'])),rs=Array.isArray(e.results)?e.results:[];rs.forEach(function(r,i){var rank=int_(prop_(r,['rank','position','Position']))||i+1,k=int_(prop_(r,['kills','Kills'])),b=int_(prop_(r,['booyahs','Booyahs'])),pp=num_(prop_(r,['positionPoints','Position Points'])),kp=num_(prop_(r,['killPoints','Kill Points']))||k,total=num_(prop_(r,['total','Total','totalPoints','Total Points']))||pp+kp;out.push({resultId:clean_(prop_(r,['resultId','Result ID','id']))||eid+'-R-'+(i+1),eventId:eid,eventName:en,teamId:clean_(prop_(r,['teamId','Team ID'])),teamName:clean_(prop_(r,['teamName','Team Name','Team','name'])),position:rank,kills:k,booyahs:b,positionPoints:pp,killPoints:kp,totalPoints:total,proofUrl:clean_(prop_(r,['proofUrl','Proof URL','ProofURL'])),verified:bool_(prop_(r,['verified','Verified'])),updatedAt:now_()})})});return out}
function readEvents_(){var events=read_(TABS.EVENTS),results=read_(TABS.RESULTS),by={};results.forEach(function(r){var eid=clean_(prop_(r,['eventId','Event ID']));if(!eid)return;(by[eid]||(by[eid]=[])).push({resultId:clean_(prop_(r,['resultId','Result ID'])),teamId:clean_(prop_(r,['teamId','Team ID'])),teamName:clean_(prop_(r,['teamName','Team Name'])),rank:int_(prop_(r,['position','Position']))||1,kills:int_(prop_(r,['kills','Kills'])),booyahs:int_(prop_(r,['booyahs','Booyahs'])),positionPoints:num_(prop_(r,['positionPoints','Position Points'])),killRatio:0,booyahRatio:0,total:num_(prop_(r,['totalPoints','Total Points','total','Total']))});});return events.map(function(e){var eid=clean_(prop_(e,['eventId','Event ID','id']));return Object.assign(e,{eventId:eid,results:by[eid]||[]})})}
function readAnnouncements_(){return read_(TABS.ANNOUNCEMENTS).map(function(a){return{announcementId:clean_(prop_(a,['announcementId','Announcement ID','id'])),id:clean_(prop_(a,['announcementId','Announcement ID','id'])),name:clean_(prop_(a,['tournamentName','Tournament Name','name'])),tournamentName:clean_(prop_(a,['tournamentName','Tournament Name'])),organizer:clean_(prop_(a,['organizationName','Organization Name','organizer'])),organizationName:clean_(prop_(a,['organizationName','Organization Name'])),organizerUrl:clean_(prop_(a,['organizationUrl','Organization URL','organizerUrl'])),registrationUrl:clean_(prop_(a,['registrationUrl','Registration URL'])),date:clean_(prop_(a,['tournamentDate','Tournament Date','date'])),tournamentDate:clean_(prop_(a,['tournamentDate','Tournament Date'])),prize:clean_(prop_(a,['prizePool','Prize Pool','prize'])),prizePool:clean_(prop_(a,['prizePool','Prize Pool'])),totalSlots:int_(prop_(a,['totalSlots','Total Slots'])),registeredSlots:int_(prop_(a,['registeredSlots','Registered Slots'])),stage:clean_(prop_(a,['stage','Stage']))||'Upcoming',status:clean_(prop_(a,['status','Status']))||'Official',notes:clean_(prop_(a,['description','Description','notes'])),description:clean_(prop_(a,['description','Description','notes'])),published:bool_(prop_(a,['published','Published'])),createdAt:clean_(prop_(a,['createdAt','Created At'])),updatedAt:clean_(prop_(a,['updatedAt','Updated At']))};}).filter(function(a){return!!a.name})}
function validUrl_(v){try{var u=new URL(clean_(v));return u.protocol==='https:'||u.protocol==='http:'}catch(e){return false}}
function validateAnnouncements_(items){if(items.length>MAX_ROWS-1)throw new Error('Tournament announcements exceed the supported limit.');var ids={};items.forEach(function(a){var id=clean_(prop_(a,['announcementId','Announcement ID','id']))||id_('ANN');if(ids[id])throw new Error('Duplicate announcement ID: '+id);ids[id]=1;var name=clean_(prop_(a,['tournamentName','Tournament Name','name']));if(!name)throw new Error('Every tournament announcement needs a tournament name.');var org=clean_(prop_(a,['organizationName','Organization Name','organizer']));if(!org)throw new Error(name+': organization name is required.');var stage=clean_(prop_(a,['stage','Stage']))||'Upcoming';if(['Upcoming','Started','Ongoing','Completed'].indexOf(stage)===-1)throw new Error(name+': invalid tournament stage.');var total=int_(prop_(a,['totalSlots','Total Slots'])),registered=int_(prop_(a,['registeredSlots','Registered Slots']));if(registered>total)throw new Error(name+': registered slots cannot exceed total slots.');if(bool_(prop_(a,['published','Published']))){if(total<=0)throw new Error(name+': total slots must be greater than 0 before publishing.');if(!validUrl_(prop_(a,['registrationUrl','Registration URL'])))throw new Error(name+': registration URL must be http(s) before publishing.');if(!validUrl_(prop_(a,['organizationUrl','Organization URL','organizerUrl'])))throw new Error(name+': organization URL must be http(s) before publishing.');}})}
function saveTeams_(items){var stamp=now_(),old=readTeams_(),byId={},byName={};old.forEach(function(t){byId[t.teamId]=t;byName[t.teamName.toLowerCase()]=t});var out=[],used={};(items||[]).forEach(function(x){var name=clean_(prop_(x,['teamName','Team Name','Team']));if(!name)return;var oldx=byId[clean_(prop_(x,['teamId','Team ID','id']))]||byName[name.toLowerCase()]||{};var sl=clean_(prop_(x,['slug','Slug']))||oldx.slug||slug_(name),base=sl,z=2;while(used[sl.toLowerCase()])sl=base+'-'+z++;used[sl.toLowerCase()]=1;out.push({teamId:clean_(prop_(x,['teamId','Team ID','id']))||oldx.teamId||id_('TEAM'),teamName:name,slug:sl,logoUrl:clean_(prop_(x,['logoUrl','Logo URL','LogoURL']))||oldx.logoUrl||'',bannerUrl:clean_(prop_(x,['bannerUrl','Banner URL']))||oldx.bannerUrl||'',description:clean_(prop_(x,['description','Description']))||oldx.description||'',mobileNumber:clean_(prop_(x,['mobileNumber','Mobile Number']))||oldx.mobileNumber||'',status:clean_(prop_(x,['status','Status']))||oldx.status||'Active',registrationStatus:clean_(prop_(x,['registrationStatus','Registration Status']))||oldx.registrationStatus||'Registered',createdAt:clean_(prop_(x,['createdAt','Created At']))||oldx.createdAt||stamp,updatedAt:stamp,roster:Array.isArray(x.roster)?x.roster:(oldx.roster||[])});});write_(TABS.TEAMS,out);var ro=[];out.forEach(function(t){(t.roster||[]).forEach(function(p,i){var name=clean_(prop_(p,['name','playerName','Player Name'])),uid=clean_(prop_(p,['uid','UID'])),logo=clean_(prop_(p,['playerLogoUrl','Player Logo URL']));if(!name&&!uid&&!logo)return;ro.push({playerId:clean_(prop_(p,['playerId','Player ID','id']))||t.teamId+'-P-'+(i+1),teamId:t.teamId,teamName:t.teamName,playerName:name,uid:uid,role:clean_(prop_(p,['role','Role'])),playerLogoUrl:logo,status:clean_(prop_(p,['status','Status']))||'Active',createdAt:clean_(prop_(p,['createdAt','Created At']))||stamp,updatedAt:stamp});});});write_(TABS.ROSTERS,ro)}
function saveEvents_(items){var incoming=Array.isArray(items)?items:[],old=read_(TABS.EVENTS),by={};old.forEach(function(e){by[clean_(prop_(e,['eventId','Event ID']))]=e});var stamp=now_(),out=[];incoming.forEach(function(x){var eid=clean_(prop_(x,['eventId','Event ID','id'])),oldx=by[eid]||{};out.push({eventId:eid||oldx.eventId||id_('EVENT'),name:clean_(prop_(x,['name','Name','eventName'])),organizer:clean_(prop_(x,['organizer','Organizer'])),organizerUrl:clean_(prop_(x,['organizerUrl','Organizer URL'])),registrationUrl:clean_(prop_(x,['registrationUrl','Registration URL'])),teams:int_(prop_(x,['teams','Teams'])),totalSlots:int_(prop_(x,['totalSlots','Total Slots'])),registeredSlots:int_(prop_(x,['registeredSlots','Registered Slots'])),prize:clean_(prop_(x,['prize','Prize','Prize Pool'])),status:clean_(prop_(x,['status','Status']))||'Pending',stage:clean_(prop_(x,['stage','Stage']))||'Upcoming',counted:clean_(prop_(x,['counted','Counted'])),date:clean_(prop_(x,['date','Date','Event Date'])),notes:clean_(prop_(x,['notes','Notes'])),matchesPlayed:int_(prop_(x,['matchesPlayed','Matches Played'])),published:bool_(prop_(x,['published','Published'])),createdAt:clean_(prop_(x,['createdAt','Created At']))||oldx.createdAt||stamp,updatedAt:stamp});});write_(TABS.EVENTS,out);var explicit=false;incoming.forEach(function(x){if(Object.prototype.hasOwnProperty.call(x,'results'))explicit=true});if(explicit){write_(TABS.RESULTS,resultRowsForEvents_(incoming))}}
function saveAnnouncements_(items){var incoming=Array.isArray(items)?items:[],old=readAnnouncements_(),by={};old.forEach(function(a){by[a.announcementId]=a});var stamp=now_(),out=incoming.map(function(x){var aid=clean_(prop_(x,['announcementId','Announcement ID','id'])),oldx=by[aid]||{};return{announcementId:aid||oldx.announcementId||id_('ANN'),tournamentName:clean_(prop_(x,['tournamentName','Tournament Name','name'])),organizationName:clean_(prop_(x,['organizationName','Organization Name','organizer'])),organizationUrl:clean_(prop_(x,['organizationUrl','Organization URL','organizerUrl'])),registrationUrl:clean_(prop_(x,['registrationUrl','Registration URL'])),tournamentDate:clean_(prop_(x,['tournamentDate','Tournament Date','date'])),prizePool:clean_(prop_(x,['prizePool','Prize Pool','prize'])),totalSlots:int_(prop_(x,['totalSlots','Total Slots'])),registeredSlots:int_(prop_(x,['registeredSlots','Registered Slots'])),stage:clean_(prop_(x,['stage','Stage']))||'Upcoming',status:clean_(prop_(x,['status','Status']))||'Official',description:clean_(prop_(x,['description','Description','notes'])),published:bool_(prop_(x,['published','Published'])),createdAt:clean_(prop_(x,['createdAt','Created At']))||oldx.createdAt||stamp,updatedAt:stamp}});validateAnnouncements_(out);write_(TABS.ANNOUNCEMENTS,out)}
function publicData_(){return{teams:readTeams_(),rankings:read_(TABS.RANKINGS),events:readEvents_(),rankingResults:read_(TABS.RESULTS),results:read_(TABS.RESULTS),announcements:readAnnouncements_().filter(function(a){return a.published===true}),news:read_(TABS.NEWS),achievements:read_(TABS.ACHIEVEMENTS),collaborators:read_(TABS.COLLAB),serverTime:now_(),version:VERSION}}
function adminData_(){var p=publicData_();p.accounts=read_(TABS.ACCOUNTS);p.submissions=read_(TABS.SUBMISSIONS);p.feedback=read_(TABS.FEEDBACK);p.announcements=readAnnouncements_();return p}
function doGet(){try{ensureAll_();return ok_(publicData_())}catch(e){return fail_(err_(e),'READ_FAILED')}}
function doPost(e){var lock=LockService.getScriptLock();try{if(!e||!e.postData||!e.postData.contents)return fail_('Empty request body','EMPTY_BODY');if(e.postData.contents.length>MAX_BODY_CHARS)return fail_('Request is too large','BODY_TOO_LARGE');var p=JSON.parse(e.postData.contents),action=clean_(p.action||'').toLowerCase();lock.waitLock(20000);if(action==='setup'||action==='setupsheets')return setupTNFFM();if(action==='health'||action==='healthcheck')return ok_({healthy:true,spreadsheet:getSS_().getName(),tabs:Object.keys(HEADERS).map(function(k){return HEADERS[k]?k:null}).filter(Boolean)});if(action==='loginteam'){var username=clean_(p.username),accounts=read_(TABS.ACCOUNTS),account=accounts.find(function(a){return clean_(prop_(a,['username','Username']))===username});if(!account)throw new Error('Team account not found.');var stored=clean_(prop_(account,['passwordHash','PasswordHash']));if(stored!==clean_(p.password))throw new Error('Invalid username or password.');return ok_({account:{username:username,teamSlug:clean_(prop_(account,['teamSlug','TeamSlug'])),status:clean_(prop_(account,['status','Status']))||'Active'}})}if(action==='submitfinalleaderboard'){var sub=read_(TABS.SUBMISSIONS);sub.push({submissionId:clean_(p.submissionId)||id_('SUB'),username:clean_(p.username),teamSlug:clean_(p.teamSlug),team:clean_(p.team),tournamentName:clean_(p.tournamentName),tournamentDate:clean_(p.tournamentDate),organizerName:clean_(p.organizerName),prizePool:clean_(p.prizePool),finalPosition:clean_(p.finalPosition),finalLeaderboard:clean_(p.finalLeaderboard),proofUrl:clean_(p.proofUrl),status:'Pending',reviewNotes:'',reviewedBy:'',reviewedAt:'',createdAt:now_()});write_(TABS.SUBMISSIONS,sub);return ok_({saved:true})}if(action==='submitfeedback'){var fb=read_(TABS.FEEDBACK);fb.push({feedbackId:id_('FDB'),username:clean_(p.username),teamSlug:clean_(p.teamSlug),team:clean_(p.team),message:clean_(p.message),status:'Open',adminReply:'',createdAt:now_(),updatedAt:now_()});write_(TABS.FEEDBACK,fb);return ok_({saved:true})}
var changed=[];if(Array.isArray(p.teams)){saveTeams_(p.teams);changed.push('teams')}if(Array.isArray(p.rankings)){write_(TABS.RANKINGS,p.rankings);changed.push('rankings')}if(Array.isArray(p.events)){saveEvents_(p.events);changed.push('events')}if(Array.isArray(p.announcements)){saveAnnouncements_(p.announcements);changed.push('announcements')}if(Array.isArray(p.news)){write_(TABS.NEWS,p.news);changed.push('news')}if(Array.isArray(p.achievements)){write_(TABS.ACHIEVEMENTS,p.achievements);changed.push('achievements')}if(Array.isArray(p.collaborators)){write_(TABS.COLLAB,p.collaborators);changed.push('collaborators')}if(Array.isArray(p.accounts)){write_(TABS.ACCOUNTS,p.accounts);changed.push('accounts')}if(Array.isArray(p.submissions)){write_(TABS.SUBMISSIONS,p.submissions);changed.push('submissions')}if(Array.isArray(p.feedback)){write_(TABS.FEEDBACK,p.feedback);changed.push('feedback')}if(!changed.length)return fail_('No supported data section was supplied.','NO_DATA');SpreadsheetApp.flush();return ok_({saved:true,verified:true,changed:changed,counts:{teams:readTeams_().length,rankings:read_(TABS.RANKINGS).length,events:read_(TABS.EVENTS).length,eventResults:read_(TABS.RESULTS).length,announcements:readAnnouncements_().length,news:read_(TABS.NEWS).length,achievements:read_(TABS.ACHIEVEMENTS).length,collaborators:read_(TABS.COLLAB).length,submissions:read_(TABS.SUBMISSIONS).length,feedback:read_(TABS.FEEDBACK).length}})}catch(e){return fail_(err_(e),'WRITE_FAILED')}finally{try{lock.releaseLock()}catch(e){}}}
function setSpreadsheetId_(id){id=clean_(id);if(!id)throw new Error('Spreadsheet ID is required.');SpreadsheetApp.openById(id);PropertiesService.getScriptProperties().setProperty('SPREADSHEET_ID',id);SS_=null;return ok_({message:'SPREADSHEET_ID saved.'})}
function setSpreadsheetId(id){return setSpreadsheetId_(id)}
