import Link from "next/link";
import { CalendarDays, ExternalLink, Link2, Trophy, Users } from "lucide-react";
import { Header } from "@/components/Header";
import { getPublishedTrackedEvents, type TrackedEvent } from "@/lib/events";
export const metadata={title:"Tournament Announcements | TNFFM Community Rankings",description:"Organization tournament promotions, registration links, schedules and live slot status from TNFFM."};
export const dynamic="force-dynamic"; export const revalidate=0;
function stage(e:TrackedEvent){return String(e.stage||"Upcoming").trim()||"Upcoming"}
function Card({e}:{e:TrackedEvent}){const total=Math.max(0,Number(e.totalSlots)||0),registered=Math.min(total||Number.MAX_SAFE_INTEGER,Math.max(0,Number(e.registeredSlots)||0));return <article className="group overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-white/[.06] via-black/40 to-black/70 p-5 shadow-xl transition hover:-translate-y-1 hover:border-gold/40 sm:p-6"><div className="flex items-start justify-between gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl border border-gold/25 bg-gold/10 text-gold"><Trophy className="h-6 w-6"/></div><span className="rounded-full border border-gold/30 bg-gold/10 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-gold">{stage(e)}</span></div><h2 className="mt-5 font-rajdhani text-2xl font-bold uppercase leading-tight text-white sm:text-3xl">{e.name}</h2><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">Organized by {e.organizer||"Organization"}</p><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-400">{e.notes||"Tournament details will be updated by the organizer."}</p><div className="mt-5 grid grid-cols-2 gap-3"><Info icon={<CalendarDays/>}label="Date"value={e.date||"TBA"}/><Info icon={<Trophy/>}label="Prize Pool"value={e.prize||"TBA"}gold/><Info icon={<Users/>}label="Slots"value={total?`${registered}/${total}`:"TBA"}/><Info label="Status"value={e.status||"Official"}/></div><div className="mt-5 flex flex-wrap gap-2 border-t border-white/10 pt-4">{e.registrationUrl&&<a href={e.registrationUrl}target="_blank"rel="noreferrer"className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-gold px-4 py-2 text-xs font-black uppercase text-black hover:brightness-110"><Link2 className="h-4 w-4"/>Register Now</a>}{e.organizerUrl&&<a href={e.organizerUrl}target="_blank"rel="noreferrer"className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-xs font-bold text-white hover:border-gold/40 hover:text-gold"><ExternalLink className="h-4 w-4"/>Organization Page</a>}<Link href="/tracked-events"className="inline-flex min-h-10 items-center rounded-lg border border-white/10 px-4 py-2 text-xs font-bold text-slate-300 hover:text-gold">Event Details</Link></div></article>}
function Info({icon,label,value,gold=false}:{icon?:React.ReactNode;label:string;value:string;gold?:boolean}){return <div className="rounded-xl border border-white/5 bg-black/30 p-3"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">{icon&&<span className="h-3.5 w-3.5 [&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span>}{label}</div><p className={`mt-1 text-sm font-semibold ${gold?"text-gold":"text-slate-200"}`}>{value}</p></div>}
export default async function TournamentAnnouncementsPage(){const events=await getPublishedTrackedEvents();const upcoming=events.filter(e=>stage(e)==="Upcoming").length;const started=events.filter(e=>stage(e)==="Started").length;const ongoing=events.filter(e=>stage(e)==="Ongoing").length;const totalSlots=events.reduce((s,e)=>s+(Number(e.totalSlots)||0),0);return <main className="min-h-screen min-w-0 overflow-x-hidden"><Header/><section className="mx-auto w-full max-w-7xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8"><div className="max-w-4xl"><p className="font-rajdhani text-xs font-black uppercase tracking-[.24em] text-gold sm:text-sm">TNFFM Community</p><h1 className="mt-2 font-rajdhani text-4xl font-black uppercase leading-none text-white sm:text-6xl">Tournament Announcements</h1><p className="mt-4 text-sm leading-6 text-slate-400 sm:text-base">Promoted organization tournaments with registration links, organization pages, schedules, prize pools, slot availability and complete tournament information.</p></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Upcoming"value={upcoming}/><Stat label="Started"value={started}/><Stat label="Ongoing"value={ongoing}/><Stat label="Total Slots"value={totalSlots}/></div>{events.length?<div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{events.map(e=><Card key={`${e.id||e.name}-${e.date}`}e={e}/>)}</div>:<div className="glass mt-8 rounded-2xl p-12 text-center"><Trophy className="mx-auto h-10 w-10 text-gold"/><h2 className="mt-4 font-rajdhani text-2xl font-bold uppercase text-white">No tournament announcements yet</h2><p className="mt-2 text-sm leading-6 text-slate-400">Published organization tournaments will appear here automatically.</p></div>}</section></main>}
function Stat({label,value}:{label:string;value:number}){return <div className="glass rounded-xl p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 font-rajdhani text-3xl font-bold text-gold">{value}</p></div>}
